### PR TITLE
Basic API that collects data from power to fly website

### PR DESCRIPTION
**Pull request by RashikaKarki**
I have created a basic flask api. As of now I have only scraped data from power to fly website though I am planning to add couple more website here. Also, I have added readme so it will be easy for you all to access the api.

Can you all review it?

Partially solves #1

### CODE REVIEW

**Review by anjalisoni3655 — APPROVED** [review]
LGTM! Where are you planning to host it?

**Comment by RashikaKarki** [comment]
@anjalisoni3655 
For now I will go with Heroku but later if time permits I will give it a go with Linode. Guess we have a sponsor prize for best use of it and ofcourse the free credits 🙈

**Review by ayushmasharma — APPROVED** [review]
Looks Perfect!

**Comment by anjalisoni3655** [comment]
> @anjalisoni3655 
> For now I will go with Heroku but later if time permits I will give it a go with Linode. Guess we have a sponsor prize for best use of it and ofcourse the free credits 🙈

Yah, definitely.

**Pull request merged**
